### ISSUE TITLE
"Apply incoming filters" property missing

### ISSUE THREAD

**Issue by ElhemEnohpi** [peci1/filtaquilla#1]
Hi peci1, and thanks for updating Filtaquilla! I tried it out and it's partially working, but there seems to be a problem with the "Apply incoming filters" property. This should show up in a folder's "Properties/General Information" tab. I can see a line that says "Enabled   Inherit". Below that should be a line saying "Apply Incoming Filters" with checkboxes below Enabled and Inherit, but it's missing. The filters don't get applied to IMAP subfolders.

**Comment by peci1** [comment]
Hello @ElhemEnohpi, thank you for reporting the bug. However, in my Thunderbird, the Apply incoming filters fields are displayed. I specifically remember there was a code change needed for them to work in TB 60, and I did that change. So it's strange it works for me and not for you.

Which version of TB and Filtaquilla are you using? How did you install Filtaquilla?

Are there some related logs in the error console? (you can open it with Ctrl+Shift+J).

Thank you for the further info needed for resolving this bug...

**Comment by peci1** [comment]
Might it be an interference with Junquilla? I don't use it, so I wouldn't discover that... Can you try it with Junquilla disabled?

**Comment by ElhemEnohpi** [comment]
Yes, if I disable Junquilla, then Filtaquilla works. The "Apply Incoming Filters" and checkboxes appear, and the filters run correctly when getting new mail. Fyi, they have always worked fine together in the past.

**Comment by peci1** [comment]
Junquilla does not support TB 60. Or have you also found an experimental version?

**Comment by peci1** [comment]
Then somebody has to update Junquilla for TB 60. I'm not using it and I'm not very much into maintaining addons I don't use... 

I tried contacting the original author, but it seems he no longer replies to the support email he published with filtaquilla. Now Thunderbird people will try if they can find another working email of him. In case they succeed contacting him, we can ask if he can still maintain the addon. If he won't answer, somebody else would have to take over maintaining of junquilla. As a starting point for the needed changes, the [diff of filtaquilla between versions 1.3 and 1.4](https://github.com/peci1/filtaquilla/compare/3aa14...master) can be used.

**Comment by ElhemEnohpi** [comment]
Ok, thanks. I also tried a couple of times to contact the author, Kent James, but he didn't answer. Maybe you saw Wayne Mery's comment on Mozillazine forum, that Kent has retired from programming, and won't maintain it, but he's happy if other people do. I don't have very much experience with Javascript, but when I have some time I'll try to modify Junquilla, hopefully to fix it but maybe just to remove that part of the code because I don't really need it. I'll post it somewhere if I get it to work...
