### ISSUE TITLE
Port to Thunderbird 60+?

### ISSUE THREAD

**Issue by iago-lito** [peci1/filtaquilla#2]
Hey, I cannot use FiltaQuilla anymore since I upgraded Thunderbird to 60.  

How bad is this broken compatibility?  
Is there any plan making fq compatible with tb 60+?  
How much work does this represent ?

This is it, thank you for support :)

**Comment by peci1** [comment]
Just try it, this version is compatible with TB 60 (and I think up to 62). Install manually from https://github.com/peci1/filtaquilla/releases/download/1.4.0/filtaquilla.mesquilla.com.1.4.0.xpi (official release to TB addons site still hangs on the verification step which I can't make any faster).

**Comment by iago-lito** [comment]
Awesome. This works fine. And I'm glad it's just a matter of verification time :) Cheers!
