### ISSUE TITLE
DetachAttachmentsTo will create a seond email

### ISSUE THREAD

**Issue by Olifair** [peci1/filtaquilla#3]
I have just installed the new version 1.4.0 on my newly installed Thunderbird 60.3.0 (32 bits) on my brandnew Windows 10 64 bit computer, and it basically runs fine. However I still have a problem that i already had on Thunderbird 52.9.1 and FiltaQuilla 1.3.2 : 
I have created a filter that is only executed manually, that looks at the attachment status, and only if an email has an attachment, then I use the Action "DetachAttachmentsTo", to save the attachment to a temp folder. I basically would like to use this every now and then on my sent email folder and get rid of all the attached files. I have tested this on a test-IMAP folder, and when I apply this filter, then I get all emails twice, one with and one without attachment.  Anything I'm doing wrong or is this a bug in Fitlaquilla ? 

Cheers

Oliver

**Comment by peci1** [comment]
I tested quickly on one email (TB 60, FQ 1.4.0), and I can't replicate the behavior you described. Did you try with all other addons disabled?

**Comment by Olifair** [comment]
Hello Peci1, 
I get this behaviour from about 273 of the emails I try it on. I have tried without other add-ons or extensions, same thing. I have tried to put these emails in an extra folder, and apply filter to folder (I have also taken outa ll other filters), I have also tried to apply filter only on selected emails. Always the same, on some emails I get the original plus one with the attachment detached. I had a quick look at the source of the emails : I cannot see any evident difference in the headers. But if you are interested I could take some time and copy the anonymous parts of the headers of some emails where it works and of the ones where it does not work (and before and after). 
Great that you have take on this plugin and made it available for Thuderbird 60. Thanks a lot
Cheers

Oliver

**Comment by peci1** [comment]
Hi, it'd be really helpful to have the sources of some emails that are affected. 

Also, did you try detaching the attachments of these emails manually via right-clicking them in the mail window?

**Comment by Olifair** [comment]
Sorry, need to find some times to put together some headers. Normal detaching or deleting of attachments has never been a problem.

**Comment by peci1** [comment]
Hi, there's another developer who took over FiltaQuilla development. Just try updating to the lastest version from official addons repo. If the bug is still there, please, contact the new developer Axel Grude.
