### ISSUE TITLE
Question: Junquilla

### ISSUE THREAD

**Issue by cleidigh** [peci1/filtaquilla#4]
@peci1 
Just saw your post on the Mozilla site.  I am looking at various extensions which have broken and since you did the nice work on filtaqulla I was wondering if you used were possibly working junquilla?

After looking at the thread I was able to get together extension working but it's a really small one.
If you are not planning working on the other extension, I might give it a crack.

What is appropriate these days for updating and publishing an existing extension like you did?
Permission from the original author?  

Cheers
Christopher

**Comment by peci1** [comment]
Hey, Christopher. I don't have any plans with Junquilla.

You may try to get in touch with Axel who has succeeded taking over FiltaQuilla ( https://github.com/RealRaven2000/FiltaQuilla ). So this repo is now obsolete and I'll probably delete it in a while.

Taking over an addon has two variants: 1) you succeed contacting the original author who shares with you developer access to the addons.thunderbird.net addon page (not working with R Kent James who doesn't respond; but Axel found a way of contacting him, so he may succeed). 2) You rename the addon and publish it under this different name (which has the downside that other users are not automatically updated).

**Comment by cleidigh** [comment]
@peci1 
Thanks for the speedy reply!  I think I will contact Alex maybe I can help  him to also take over Junquilla.
